### ISSUE TITLE
sign in/registration services update

### ISSUE THREAD

**Issue by zmicier16** [rudkodm/closer-services#12]
1. Create new type of user - general app user (not merchant)
2. Ability to register with email (name, surname, email, password); Facebook; Google Plus
3. Ability to sign in with email (name, surname, email, password); Facebook; Google Plus
4. Ability restore forgotten email (send instructions to provided email)
5. Ability to log out
![screenshot_sign_in](https://cloud.githubusercontent.com/assets/21370876/20609894/80a1bc74-b2a3-11e6-8d83-35a1911dea7c.png)

**Comment by zmicier16** [comment]
username: closer.application@gmail.com
password: CloserApplication123!@#

**Comment by rudkodm** [comment]
There was some changes in admin app: https://github.com/rudkodm/closer-ui/issues/10

**Comment by rudkodm** [comment]
This functionality is available using Auth0 API. I've enable Google and Facebook login options in Auth0 profile. Mandatory fields could be configured on client side additionally
 ___ !!! Later, we have to register application on Facebook and Google, and add AppID to Auth0 configs !!! ___, but for now, we could use developers keys.

There were minor changes in admin app - to be on the same page with mobile client.

## Implementation details:
1. user role could be added on client side manually to 'userProfile.user_metadata.roles'. Also it is possible to use Auth0 rule, to do it automatically: [example from admin app](https://github.com/rudkodm/closer-ui/blob/master/auth0/rules/set-roles-to-users.js)
